### PR TITLE
Fixed bug with flame and bullet animation.

### LINKED ISSUE #15: 'display()' problem with non-simple textures
There is a small problem with displaying not simple textures (like flame animations or bullets with various directions). Probably is related to : https://github.com/pietrik123/untitled-sdl-tank-game/commit/971e0e196bf8a07b145de136b4595462d3c8e2d8 and corresponding issue: https://github.com/pietrik123/untitled-sdl-tank-game/issues/12

obraz

obraz

For example (in Game.cpp , `Game::mainLoop()`) :

```cpp
for (flameIt = flames.begin(); flameIt != flames.end(); ++flameIt) {
    Flame &flame = (*flameIt);
    flame.myTex.renderAnim(renderer,
        getPosXOnScreen(flame.posX),
        getPosYOnScreen(flame.posY),
        MyTexture::RENDER_IN_CENTER, 5, flame.texFrame);
}
```
was replaced by ...

```cpp
flame.display(renderer, this);
```
which calls `MyTexture::render()` instead of `MyTexture::renderAnim()`

### PR DESCRIPTION
**Pull request by dante7867**
Issue number: #15.
Back to previous version, f.ex.:
```cpp
       for (flameIt = flames.begin(); flameIt != flames.end(); ++flameIt) {
            Flame &flame = (*flameIt);    
			flame.myTex.renderAnim(renderer,
                getPosXOnScreen(flame.posX),
                getPosYOnScreen(flame.posY),
                MyTexture::RENDER_IN_CENTER, 5, flame.texFrame);
        }
```

### CODE REVIEW

File: untitled-sdl-tank-game/Game.cpp [hunk 1]
```diff
@@ -513,12 +513,20 @@ void Game::mainLoop()
         }
 
         for (bulletIt = bullets.begin();bulletIt != bullets.end(); ++bulletIt) {
-            (*bulletIt).display(renderer, this);
+            (*bulletIt).myTex.render(renderer,
+                getPosXOnScreen((*bulletIt).posX),
+                getPosYOnScreen((*bulletIt).posY),
+                MyTexture::RENDER_IN_CENTER,
+                (*bulletIt).getDirectionAngle());
+
```
Comment (pietrik123) [inline untitled-sdl-tank-game/Game.cpp]: please remove empty line

File: untitled-sdl-tank-game/untitled-sdl-tank-game.vcxproj [hunk 2]
```diff
@@ -23,7 +23,7 @@
     <ProjectGuid>{c9010400-c373-47b2-9341-8a33c0ba718f}</ProjectGuid>
     <Keyword>Win32Proj</Keyword>
     <RootNamespace>untitled_sdl_tank_game</RootNamespace>
-    <WindowsTargetPlatformVersion>10.0.14393.0</WindowsTargetPlatformVersion>
```
Comment (pietrik123) [inline untitled-sdl-tank-game/untitled-sdl-tank-game.vcxproj:26]: we will have to take common version of win sdk some time. We will have to switch it manually in Visual. But it is ok for now.

**Review by pietrik123 — APPROVED** [review]
good job
